version: 0.0
os: linux

files:
  - source: target/
    destination: /home/ec2-user/app2

hooks:

  BeforeInstall:
    - location: scripts/before_install.sh

  AfterInstall:
    - location: scripts/after_install.sh

  ApplicationStart:
    - location: scripts/start_server.sh

  ApplicationStop:
    - location: scripts/stop_server.sh